name: Build and Test with Secret

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Run Jest Tests
      run: npm test

    - name: Upload Build Artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/

    - name: Use API Key
      run: echo "API Key is ${{secrets.API_KEY}}"
